### ISSUE TITLE
How can I use it in front-end ?

### ISSUE THREAD

**Issue by soulmate2015** [MaiaVictor/LJSON#12]
I want use it in front-end

example:

``` javascript
var someObj = {
    name: 'simple parallel process',
    tasks: {
        start: {type: 'start'},
        service1: {type: 'service', action: function (variables, complete) {
            return complete();
        }},
        end: {type: 'end'}
    }
};
JSON.stringify(someObj);
```

parse in back-end 

is there have a bower version, can use it in front-end site

**Comment by Kanti** [comment]
bower is not available jet. you need to download the files and include them manually both the `LJSON.js` and `Parsenhora.js` than you can use it like this:

``` js
LJSON.stringify(someObj);
```

**Comment by VictorTaelin** [comment]
I don't use Bower so I have no idea how to put it there, Kanti, do you know?

**Comment by Kanti** [comment]
I will try it

**Comment by soulmate2015** [comment]
Thanks very much.

There also have a bug when I forget `<return>` in my function.
example: 

``` javascript
var someObj = {
    tasks: {
        service1: {type: 'service', action: function (variables, complete) {
           complete();
        }}
    }
};
```

error:

```
/node_modules/LJSON/LJSON.js:36
            if (value.isApplication) 
                     ^
TypeError: Cannot read property 'isApplication' of undefined
    at normalize (/Users/wanggejun/study/node_modules/LJSON/LJSON.js:36:22)
    at normalize (/Users/wanggejun/study/node_modules/LJSON/LJSON.js:52:28)
    at normalize (/Users/wanggejun/study/node_modules/LJSON/LJSON.js:68:78)
    at normalize (/Users/wanggejun/study/node_modules/LJSON/LJSON.js:68:78)
    at normalize (/Users/wanggejun/study/node_modules/LJSON/LJSON.js:68:78)
    at Object.stringify (/Users/wanggejun/study/node_modules/LJSON/LJSON.js:78:11)
    at Object.<anonymous> (/Users/wanggejun/study/ljson.js:22:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

LJSON.js can't parse `<callback>` without `<return>` when traverse object.

**Comment by Kanti** [comment]
@soulmate2015 we are on it. See here #11
