### ISSUE TITLE
example in README fails

### ISSUE THREAD

**Issue by NodeGuy** [MaiaVictor/LJSON#8]
### test.js

``` JavaScript
var
  LJSON = require('ljson');

// client-side
function playerScript($,player){
    $("if", $("targetInRange", player, "poring"),
        $("castSpell", player, "fire bolt", $("findTarget", player, "poring")));
};
var script = LJSON.stringify(playerScript);
```

``` shell
$ node test.js 
node_modules/ljson/LJSON.js:36
            if (value.isApplication) 
                     ^

TypeError: Cannot read property 'isApplication' of undefined
    at normalize (node_modules/ljson/LJSON.js:36:22)
    at normalize (node_modules/ljson/LJSON.js:52:28)
    at Object.stringify (node_modules/ljson/LJSON.js:78:11)
    at Object.<anonymous> (.../test.js:9:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
```

**Comment by Kanti** [comment]
@MaiaVictor please Answer

**Comment by VictorTaelin** [comment]
Hey, I'm sorry. The example is missing a "return". I fixed it. Thanks.

**Comment by Kanti** [comment]
I think it would be better if no return is present the stringify function would return something like this:

``` js
"(v0,v1) => (undefined)"
```

**Comment by VictorTaelin** [comment]
I don't think that is possible... at least, I can't think a way of doing that. Also, it should return `undefined`, not `null`... Any idea?
